// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esriwfkucpwgckbdxfnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcml3Zmt1Y3B3Z2NrYmR4Zm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTMzODMsImV4cCI6MjA2NTcyOTM4M30.d9bmSsqNWKg42sZRrGdb6lmmhxaL8TMeMZv_wU_ijD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);